### ISSUE TITLE
Frontend students page

### ISSUE THREAD

**Issue by Mikxox** [SELab-2/OSOC-1#205]
## What
Create a students page based upon our figma draft.
Most functionality is currently present but a lot of styling is still needed.

Important, all of this should be done in such a way that adding new questions / removing them is easy. Reusable components for every type of question seem like a must.

- [x] Removing your suggestion
- [x] Replacing your suggestion with a new one
- [x] Admin status change has a bug when you try to use it twice on the same person
- [x] Admin status change can be done with empty value by clicking on x-mark in dropdown, this is a bug!
- [x] Every type of question should be shown correctly
- [x] Currently a multi answer question is shown as the full answer list with false / true for each.
- [x] Questions with 'other' need to be shown correctly frontend or not at all when empty
- [ ] The CV, portfolio, ... answers are a link, this could maybe be predownloaded?
- [x] Important practical information should be show at the top in a clear way so people not available can be removed quickly
- [x] Suggestions should also show their message in some way, maybe a tooltip?
- [x] Add a placeholder when loading the page the first time 'Click or drag a student to begin' or something like it.
- [x] ~~How do we remove a student? Who is allowed to remove a student?~~ trashcan + admin only
- [x] ~~Communication?~~ we're not doing this on the student page

**Comment by NielsPraet** [comment]
@Mikxox How is this going?

**Comment by Mikxox** [comment]
> @Mikxox How is this going?

Everything that is checked is included in #363 For the styling you'll have to ask @TomAlard
