### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by TomAlard** [SELab-2/OSOC-1#291]
At the moment our application is not real time. This issue proposes a couple of possible solutions.

> Het doel van dit project is om een selectietool te ontwikkelen waarin OSOC medewerkers in **real time** met elkaar kunnen samenwerken om kandidaten te selecteren en aan teams toe te wijzen.

To be clear, this means that only certain parts of the application need to be real time. Only the students and projects pages will have to support real time, pages like the users page and the editions page don't need this. When a OSOC user changes something to a project or student, this change should be visible after a short delay to all other OSOC users on the same page (without them having to refresh of course). What follows are a couple of options to achieve this:

The simplest solution seems to be polling. Polling in our case would simply mean calling the backend periodically to check if any changes were made, and updating the view if this is the case. For example, this could look something like this:

```
(Alice just tabbed to the students page. Assume the backend is polled every two seconds).

12:00:00 Alice - GET /api/testEdition/students  (Initialize the page)
12:00:02 Alice - GET /api/testEdition/students  (Any changes? No, the data is discarded)
12:00:04 Alice - GET /api/testEdition/students  (Any changes? No, the data is discarded)
12:00:05 Bob   - POST /api/testEdition/students/testStudentId/status  (Bob updates the status of a student)
12:00:06 Alice - GET /api/testEdition/students  (Any changes? Yes, update the student with testStudentId)
12:00:08 Alice - GET /api/testEdition/students  (Any changes? No, the data is discarded)
...
```
Pros:
- Does not require changing the backend at all
- Comparatively simple to implement

Cons:
- Wastes a lot of resources, therefore it does not scale well
- Essentially the equivalent of hitting the refresh button every X seconds

A more sophisticated solution is [WebSocket](https://en.wikipedia.org/wiki/WebSocket). WebSocket is different from HTTP, as it allows for two-way (full-duplex) communication over a single TCP connection, where HTTP only allows for one-way communication. In other words, this would allow the backend to tell the frontend when a change was made by sending an event. The example from above could then look like this:

```
(Alice just tabbed to the students page).
12:00:00 Alice  - GET /api/testEdition/students  (Initialize the page)
12:00:05 Bob    - Sends a WebSocket message to the server to update the status of a student
12:00:05 Server - Broadcasts that the student with testStudentId was modified
12:00:05 Alice  - Receives the broadcasted message from the server and updates the student
```
Pros:
- Scales well, as there is no wasted traffic
- WebSockets are supported by Spring (see [here](https://spring.io/guides/gs/messaging-stomp-websocket/#initial) for example)

Cons:
- Would require changes to the backend
- Comparatively difficult to implement
- Swagger/OpenAPI does not support Websockets (see [here](https://stackoverflow.com/questions/38186483/describe-websocket-api-via-swagger) or [here](https://stackoverflow.com/questions/33146339/in-swagger-is-it-possible-to-create-apis-for-websockets)), so we'll have to find another way to document this part of the API.

A last solution would be to use [Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events). The difference between SSE and WebSockets is explained [here](https://stackoverflow.com/questions/5195452/websockets-vs-server-sent-events-eventsource). I did not look further into this, as it seems that SSE's only allow communication from the server to the client, but we could also go for this hacky solution:
>Chat is perfectly doable with SSE – you can use regular POST to send messages to the server.

Personally, I think going for WebSockets/SSE's could be [premature optimization](https://stackify.com/premature-optimization-evil/), and that we'd be better off trying polling first. I'd like to hear your thoughts on this though.

**Comment by Mikxox** [comment]
I'm not a big fan of polling mainly because reloading the projects page can take a thousand requests if you've done some scrolling. It might be more doable if we change the polling time to something like 10+ seconds. Doing auto polling should only take a few lines of code frontend so I'd propose having a look at websockets to see how doable that would be since spring has websocket support and react has SockJS and react-stomp .

**Comment by NinjaJay** [comment]
I think we should look further into websockets. It is more difficult but once it's implemented it doesn't have much cons while polling might be easier to implement but I think polling is used for more temporary solutions.

**Comment by TomAlard** [comment]
> I'm not a big fan of polling mainly because reloading the projects page can take a thousand requests if you've done some scrolling.

A thousand requests seems like a lot, is this because of the serialized URL's? Do you think a thousand requests every 2-4 seconds for each user would be too much traffic for the server to handle? If that is why you are dismissing polling, I think that's [premature optimization](https://stackify.com/premature-optimization-evil/). I think we should first implement polling since it's rather easy to set up. We could then do a "stress test" by having a couple of us using the frontend on our server at the same time. If the performance drops below an acceptable level, then we'll know using something more complicated like websockets is justified. What do you think?

> Doing auto polling should only take a few lines of code frontend so I'd propose having a look at websockets

Could you clarify what you mean with this? I'm reading this as "polling is easy to implement so we should do websockets", which isn't making much sense to me.

**Comment by TomAlard** [comment]
> I think polling is used for more temporary solutions.

I don't think this is a valid argument against using polling.

**Comment by Mikxox** [comment]
> > I'm not a big fan of polling mainly because reloading the projects page can take a thousand requests if you've done some scrolling.
> 
> A thousand requests seems like a lot, is this because of the serialized URL's? Do you think a thousand requests every 2-4 seconds for each user would be too much traffic for the server to handle? If that is why you are dismissing polling, I think that's [premature optimization](https://stackify.com/premature-optimization-evil/). I think we should first implement polling since it's rather easy to set up. We could then do a "stress test" by having a couple of us using the frontend on our server at the same time. If the performance drops below an acceptable level, then we'll know using something more complicated like websockets is justified. What do you think?

I don't really know what amount would be 'a lot' and what isn't so a test, as you propose, would be good. Some code just for testing purposes should be pretty easy to write but we can discuss that at the meeting today. Websockets would be the more scalable and nicer options but I do believe we should try and finish work on every 'must have' feature first.
 
> > Doing auto polling should only take a few lines of code frontend so I'd propose having a look at websockets
> 
> Could you clarify what you mean with this? I'm reading this as "polling is easy to implement so we should do websockets", which isn't making much sense to me.

Ah no, I meant this as "polling is definitely doable to implement so we should check if websockets are doable and then just decide between the two." Again, I'm mostly worried about this taking up too much time and other stuff not getting done by the deadline. I really think websockets would be the better choice but if they are difficult to implement I think we should focus on other things first.

**Comment by TomAlard** [comment]
I've done some more research on websockets, here's what I've found:

- Websockets and a HTTP server can both run on the same port (see [here](https://stackoverflow.com/questions/29497725/can-websockets-and-http-server-both-run-on-the-same-port-number), [here](https://stackoverflow.com/questions/13791050/is-it-possible-to-enable-tcp-http-and-websocket-all-using-the-same-port) or [here](https://stackoverflow.com/questions/5969607/is-it-possible-to-use-port-80-for-both-http-and-web-socket-traffic#comment-35135305)), this means that if we wanted to use websockets, we wouldn't have to convert the entire backend to websockets. Things like the edition and user controllers wouldn't need to be changed.
- GET requests do not modify the database, therefore the student and project GET endpoints could also remain untouched, while the other endpoints get converted to websockets. It might be easier to have all the endpoints of the controller use websockets though, but I'm not sure about this.
- Converting POST/DELETE/PATCH requests to websockets should go like this: First, The frontend should subscribe to the page the user is currently on, to receive updates to the data. When the user makes a modification, the frontend would send the same payload as with the REST API to the same URL. This would, however, now be a websocket message instead of a HTTP request. The backend would then broadcast a message with what was changed (a student/project was created/modified/deleted) to all broadcasted clients. The frontend should then take action accordingly.
- **Swagger/OpenAPI does not support Websockets (see [here](https://stackoverflow.com/questions/38186483/describe-websocket-api-via-swagger) or [here](https://stackoverflow.com/questions/33146339/in-swagger-is-it-possible-to-create-apis-for-websockets)), so we'll have to find another way to document this part of the API.** I think this is a pretty significant disadvantage, so I've added it to the 'cons' of websockets.

**Comment by TomAlard** [comment]
> Websockets would be the more scalable and nicer options but I do believe we should try and finish work on every 'must have' feature first.

> Again, I'm mostly worried about this taking up too much time and other stuff not getting done by the deadline. I really think websockets would be the better choice but if they are difficult to implement I think we should focus on other things first.

For the record, I also think that websockets is a nicer solution. The reason I want to try polling first is because we have limited time remaining.

**Comment by MaartenS11** [comment]
>  Converting POST/DELETE/PATCH requests to websockets should go like this: First, The frontend should subscribe to the page the user is currently on, to receive updates to the data. When the user makes a modification, the frontend would send the same payload as with the REST API to the same URL. This would, however, now be a websocket message instead of a HTTP request. The backend would then broadcast a message with what was changed (a student/project was created/modified/deleted) to all broadcasted clients. The frontend should then take action accordingly.

That's not really how I see the web sockets being used. The general idea is that you have a single websocket that notifies the client of any changes being done on for example, the projects page or the student page(might be best to have one for each page, but one for both could also work). If the client receives this notification, the client simply refetches all information. Everything else just works the same way as it does normally, we would use the exact same GET, POST, PATCH and DELETE requests already being used by the back and frontend.

**Comment by Mikxox** [comment]
Based upon these results, I would suggest to either look at a websocket approach to at least reduce the amount of reloads needed. Or to try and reduce the amount of data reloading a student takes, a simple solution would be to reduce the 50 or so answer URLs for each student to only 1 URL since the tally form answers are about 80% of the student data and we don't even use those except for the one single student currently showing.
