### ISSUE TITLE
user email should ignore capital letters

### ISSUE THREAD

**Issue by Mikxox** [SELab-2/OSOC-1#322]
## What
When registering and using an email address with a capital letter in it, you still need to use that capital letter in the email to log in.
This is a bit weird and email address should just ignore capitalization.

## How
Probably best to fix this in the backend

**Comment by TomAlard** [comment]
Probably the easiest way to fix this is to make every email lowercase before saving it in the database. Is that an acceptable solution?

**Comment by Mikxox** [comment]
> Probably the easiest way to fix this is to make every email lowercase before saving it in the database. Is that an acceptable solution?

Of course, can you also change the attemptAuthentication function in AuthenticationFilter to use lowercase email address?
