### ISSUE TITLE
Feedback Miet

### ISSUE THREAD

**Issue by Mikxox** [SELab-2/OSOC-1#388]
## What
This is an issue about the feedback from Miet from 08/05/2022

- [x] Een motivatie bij je suggestie schrijven is niet verplicht, optioneel
Should be an easy fix

- [x] ik mis een beetje extra informatie in de studenten kaartjes links, om eenvoudiger te scannen (zie presentatie en github)
This is issue #254

- [x] Enkele filter functionaliteiten zoals "assigned to project" zouden ook nog heel handig zijn (zie presentatie)
Is worked on in #387

- [ ] Een coach kan soms nog niet in het platform zitten, als placeholder zou dat wel handig zijn.
Unsure how / if we want to do this.

~~Als je geen mail statussen voorziet, zou het wel heel handig zijn om een CV export te kunnen doen en het van daar uit aan te passen.
Don't know what is meant with this.~~

**Comment by NielsPraet** [comment]
> Als je geen mail statussen voorziet, zou het wel heel handig zijn om een CV export te kunnen doen en het van daar uit aan te passen.

This doesn't apply anymore because we do keep track of communications now
