### ISSUE TITLE
Frontend inactive editions

### ISSUE THREAD

**Issue by Mikxox** [SELab-2/OSOC-1#412]
## What
Currently frontend allows all edit / create actions on an inactive edition
Most of these actions return a not allowed error from the backend anyway, so for UI/UX purposes it would be better to disable them frontend as well.

## How
Possible fix is by adding a field 'active/inactive' to the useEdition hook and then checking if current edition is active to show buttons, allow drag events, etc.
This is probably better than doing a get to /active on every page load to compare with edition in url to know if it is active but idk about users manually changing the edition in the url so it might be needed to just to the get anyway.

**Comment by Mikxox** [comment]
This will probably be a wontfix unless somebody cares enough to do this

**Comment by lars-vc** [comment]
Showing the error in a better way could be a nice band-aid fix though
